# This workflow will generate a new config_template.yaml file whenever config.py changes.
name: Update config template

on:
  push:
    branches: [master, language_sbayes, devel]
    paths:
      - sbayes/config/config.py
      - .github/workflows/update_config_template.yml

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    steps:
    
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: bioconda, conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libproj-dev proj-data proj-bin libgeos-dev

      - name: Create conda environment
        run: |
          conda init bash
          conda create -n myenv python=${{ matrix.python-version }}

      - name: Activate conda environment
        run: |
          conda activate myenv
          conda config --set always_yes yes --set changeps1 no
          
      - name: Update conda environment
        run: |
          conda update --name base -q conda

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          python -m pip install cython numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update config_template.yaml and add/commit/push it
        run: |
          python -m sbayes.config.generate_template
          git config --global user.name "NicoNeureiter"
          git config --global user.email "nico.neureiter@gmail.com"
          git add config_template.yaml
          git commit -m "[GitHub] generated new config_template.yaml"
          git push
